---
# tasks file for cis-check
- import_tasks: section1.yml
- import_tasks: section2.yml
- import_tasks: section3.yml
- import_tasks: section4.yml
- import_tasks: section5.yml
- import_tasks: results.yml