---
- import_tasks: 3.1.yml
  tags:
    - sub3_1
    - s3
- import_tasks: 3.2.yml
  tags:
    - sub3_2
    - s3
- import_tasks: 3.3.yml
  tags:
    - sub3_3
    - s3
- import_tasks: 3.4.yml
  tags:
    - sub3_4
    - s3
- import_tasks: 3.5.yml
  tags:
    - sub3_5
    - s3
- import_tasks: 3.6.yml
  tags:
    - sub3_6
    - s3